### ISSUE TITLE
<Enhancement> Enable Display of the specific quantity of coins per denomination

### ISSUE THREAD

**Issue by amitkumar7417** [rahultheagarajan/FT07_SoftwareConfigurationManagement#1]
When a Maintainer press “Show Total Cash Held”, system should display the specific quantity of coins per denomination together with its total cash Amount/value per denomination are calculated and displayed.
Please find attachment for reference

**Before:**
![vmcs_cr e _v8_1_after](https://user-images.githubusercontent.com/37129242/45608180-fa712000-ba83-11e8-9ec7-7a9c1eb2d93f.JPG)

**After:**
![vmcs_cr e _v8_1_before](https://user-images.githubusercontent.com/37129242/45608181-fa712000-ba83-11e8-96d2-c69441032655.JPG)

**Comment by 000pyo** [comment]
**TODO**
General
- [x] Update DMR to match the new design for this enhancement

In sg.edu.nus.iss.vmcs.maintenance
- [x] Modify CoinDisplay 
- [x] Add CoinLabelItem
- [x] Add CoinLabelItemDisplay
- [x] Modify MaintenanceController 
- [x] Modify MaintenancePanel
- [x] Modify TotalCashButtonListener

In sg.edu.nus.iss.vmcs.store
- [x] Modify StoreController

**Comment by amitkumar7417** [comment]
The fix given was tested and verified to be fixed.
Assigning it for  Partner Review.
