### ISSUE TITLE
<Defect>"Show Total Cash Held" is not reset to null even after collecting the cash

### ISSUE THREAD

**Issue by amitkumar7417** [rahultheagarajan/FT07_SoftwareConfigurationManagement#2]
Follow the steps to reproduce the issue:
Step1: The maintainer push “Press To Collect All Cash” and collect all the cash and logout
Step2: Upon successfully logging out of the drinks dispenser machine, the amounts displayed
in “Show Total Cash Held” and “Press Here for Cash” of the Maintenance Panel, should
be reset to null.

**Comment by 000pyo** [comment]
*TODO*
- [x] Edit MaintenanceController to int collect cash and total cash on exit

**Comment by amitkumar7417** [comment]
The fix given was tested and verified to be fixed.
Assigning it for  Partner Review.
